#! /usr/bin/env python
"""SPDX-License: MIT; Project VUT; (C) Frank-Rene Schaefer
______________________________________________________________________________

PURPOSE: Unit Test for 'propagate_blockers' constraint propagation.

CHOICES: basic, dead_end, chain, oscillation, missing_keys, unsolvable;

DESCRIPTION:

This test verifies the constraint propagation logic used to optimize the
search space in the 'friends_pairing' algorithm.

The test prints the result of the propagation. The correctness is verified
by the HWUT framework comparing the output against a golden reference file.
Context hints are provided via '##' comments.
______________________________________________________________________________
"""
import sys
import os

# Adopt path before imports --> disable code check error E402
this_directory = os.path.join(os.path.dirname(sys.argv[0]), "../../../../../../")
sys.path.insert(0, this_directory)

from vut.engine.compare.engine.potpourri.solver.csp_arc_consistency import (propagate_blockers,  #noqa E402
                                                                     pad_ids_to_bitmask)

from vut.auxiliary.deterministic_random import DeterministicStream                                 #noqa E402

if "--hwut-info" in sys.argv:
    print("Propagate Blockers: Constraint Propagation;")
    # no CHOICE, only one functionality: 'nasty problem'
    sys.exit(0)

class Statistics:
    """Analyzes the complexity of the generated problem.
    """
    def __init__(self, lane_definition, initial_blockers, total_pads):
        # 1. Pad Distribution Stats (Density per Lane)
        self.total_pads   = total_pads
        self.total_lanes  = len(lane_definition)
        
        lane_lengths      = [len(ld) for ld in lane_definition]
        self.lane_pad_min = min(lane_lengths)
        self.lane_pad_max = max(lane_lengths)
        self.lane_pad_avg = sum(lane_lengths) / len(lane_lengths)

        # 2. Blocker Stats (Constraints per Pad)
        # We look only at pads that actually block something (Active Blockers)
        active_blocker_counts = [len(targets) for targets in initial_blockers.values()]
        
        if active_blocker_counts:
            self.block_per_pad_min = min(active_blocker_counts)
            self.block_per_pad_max = max(active_blocker_counts)
            self.block_per_pad_avg = sum(active_blocker_counts) / len(active_blocker_counts)
        else:
            self.block_per_pad_min = 0
            self.block_per_pad_max = 0
            self.block_per_pad_avg = 0.0
            
        self.total_constraints = sum(active_blocker_counts)
        self.global_block_avg  = self.total_constraints / total_pads

        # 3. Lane Aggression (Constraints originating from a Lane)
        # Sum of all blockers generated by all pads in a specific lane
        lane_constraint_counts = []
        for lane in lane_definition:
            count = 0
            for pad in lane:
                count += len(initial_blockers.get(pad, []))
            lane_constraint_counts.append(count)
            
        self.block_per_lane_min = min(lane_constraint_counts)
        self.block_per_lane_max = max(lane_constraint_counts)
        self.block_per_lane_avg = sum(lane_constraint_counts) / len(lane_constraint_counts)

    def print_report(self):
        print("# STATISTICS --------------------------")
        print("# Problem Size:")
        print("#   Total Pads:      %d" % self.total_pads)
        print("#   Total Lanes:     %d" % self.total_lanes)
        print("#")
        print("# Lane Distribution (Pads per Lane):")
        print("#   Min: %3d, Max: %3d, Avg: %.2f" % (self.lane_pad_min, self.lane_pad_max, self.lane_pad_avg))
        print("#")
        print("# Blocker Distribution (Constraints per Pad - Active Only):")
        print("#   Min: %3d, Max: %3d, Avg: %.2f" % (self.block_per_pad_min, self.block_per_pad_max, self.block_per_pad_avg))
        print("#")
        print("# Lane Aggression (Total Constraints originating from Lane):")
        print("#   Min: %3d, Max: %3d, Avg: %.2f" % (self.block_per_lane_min, self.block_per_lane_max, self.block_per_lane_avg))
        print("#")
        print("# Global Density:")
        print("#   Total Constraints: %d" % self.total_constraints)
        print("#   Avg Constraints/Pad: %.2f" % self.global_block_avg)
        print("# -------------------------------------")

def generate_lanes(M_PADS, N_LANES, rng):
    """
    Generates a lane structure with a guaranteed 'good path' and a Gaussian 
    distribution of 'bad pads' across the lanes.

    Returns:
        lane_definition: List[List[int]] - The pads in each lane.
        good_path: List[int] - The sequence of pads forming the guaranteed solution.
    """
    assert M_PADS >= N_LANES
    # 1. Setup Good Path (Guaranteed Solution)
    all_pads  = list(range(M_PADS))
    good_path = rng.sample(all_pads, N_LANES)
    
    # 2. Distribute Remaining Pads (Gaussian Distribution of Lane Counts)
    bad_pads = set(all_pads) - set(good_path)
    # Shuffle deterministically so we don't just put IDs sequentially
    bad_pads_list = rng.sample(sorted(list(bad_pads)), len(bad_pads))
    num_bad       = len(bad_pads_list)

    # Initialize lanes with good pads
    lane_definition = [[p] for p in good_path]

    # Calculate average bad pads per lane
    mu    = num_bad / float(N_LANES)
    sigma = mu / 2.0
    
    # Generate target count for each lane independently
    # This creates random fluctuations in lane density (some heavy, some light)
    target_counts = [
        rng.gauss_int(mu=mu, sigma=sigma, lower=0, upper=num_bad)
        for _ in range(N_LANES)
    ]
    
    # Normalize to ensure sum equals exactly num_bad
    current_sum = sum(target_counts)
    if current_sum == 0: current_sum = 1 # Avoid division by zero
    
    scale = num_bad / float(current_sum)
    final_counts = [int(round(c * scale)) for c in target_counts]
    
    # Fix rounding errors (dump remainder into random or first lane)
    diff = num_bad - sum(final_counts)
    final_counts[0] += diff
    
    # Fill lanes linearly
    cursor = 0
    for lane_idx, count in enumerate(final_counts):
        if count <= 0: continue
        
        chunk = bad_pads_list[cursor : cursor + count]
        lane_definition[lane_idx].extend(chunk)
        cursor += count

    # Sort lanes
    for ld in lane_definition:
        ld.sort()
        
    return lane_definition, good_path

def generate_nasty_blockers(lane_definition, good_path_set, rng, 
                            min_block_n, max_block_n):
    """
    Generates a dense set of blockers (constraints) for the given lanes.
    
    Parameters:
    - lane_definition: List of lists containing pad IDs per lane.
    - good_path_set: Set of pad IDs that constitute the guaranteed solution.
    - rng: DeterministicStream instance.
    - block_ratio_min/max: Fraction of future pads to block (0.0 to 1.0).
    
    Returns:
    - initial_blockers: Dictionary {pad_id: [blocked_pad_ids]}
    """
    initial_blockers = {}
    N_LANES = len(lane_definition)

    # Pre-calculate all pads ahead for each lane index to avoid repeated looping
    # (Optimization: flattened lists for ranges)
    pads_ahead_by_lane = []
    for i in range(N_LANES):
        ahead = []
        for future_lane in lane_definition[i+1:]:
            ahead.extend(future_lane)
        pads_ahead_by_lane.append(ahead)

    for lane_idx, lane in enumerate(lane_definition):
        pads_ahead = pads_ahead_by_lane[lane_idx]
        if not pads_ahead: continue
        
        for pad in lane:
            is_good_pad = (pad in good_path_set)
            blocked = []
            
            # Potential victims
            candidate_n = rng.next_int(int(min_block_n), int(max_block_n))
            candidates  = rng.sample(pads_ahead, min(len(pads_ahead), candidate_n))

            for victim in candidates:
                # CONSTRAINT: Good pads MUST NOT block other good pads
                # (Otherwise we destroy the guaranteed solution)
                if is_good_pad and victim in good_path_set:
                    continue
                blocked.append(victim)
            
            if blocked:
                initial_blockers[pad] = blocked

    return initial_blockers

M_PADS =  1024
N_LANES = 256

rng = DeterministicStream(0x42)

print("## Scenario: Nasty but Solvable (Deterministic).")
print("## M=%d Pads, N=%d Lanes." % (M_PADS, N_LANES))

lane_definition, good_path = generate_lanes(M_PADS, N_LANES, rng)

# 3. Generate Blockers
# (Using the extracted function from previous step)
initial_blockers = generate_nasty_blockers(lane_definition, 
                                           set(good_path), 
                                           rng, 
                                           min_block_n = 1,
                                           max_block_n = M_PADS / N_LANES)

# 4. Statistics
stats = Statistics(lane_definition, initial_blockers, M_PADS)
stats.print_report()

# 5. Run Test
lane_masks = [pad_ids_to_bitmask(ld) for ld in lane_definition]
blocker_db = [0] * M_PADS
for p, b in initial_blockers.items():
    blocker_db[p] = pad_ids_to_bitmask(b)

muritori, final_db = propagate_blockers(blocker_db, lane_masks)

if muritori is None:
    print("\n>> FAILURE: Algorithm returned Unsolvable (Good path was killed!)")
else:
    dead_good_pads = [p for p in good_path if p in muritori]
    if dead_good_pads:
        print("\n>> FAILURE: Good Path pads were killed: %s" % dead_good_pads)
    else:
        print("GOOD PADS: (%i) %s" % (len(good_path), sorted(good_path)))
        print("MURITORI:  (%i) %s" % (len(muritori), sorted(list(muritori))))
