-- SPDX-License: MIT; Project VUT; (C) Frank-Rene Schaefer
-- -------------------------------------------------------------------------
-- A DOWN STREAM, CAPTURED FROM THE REAL COMPARE ENGINE.
--
-- GENERATED by 'generate_fixture.py', never edited: a
-- fixture somebody typed would test what its author
-- BELIEVED compare emits. Subject 'alpha/WRONG/gamma'
-- against nominal 'alpha/beta/gamma'.
-- -------------------------------------------------------------------------

return {
  {
    ["field_db"] = {
      ["hwut_version"] = "2.0.0",
      ["signature"] = "mmiFiE-j4bsvTLp0iGNZEAJF9GErpfkXjVZc9Xw0yi8"
    },
    ["kind"] = "ProtocolHeader",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {
      ["analogy_begin_marker"] = "((",
      ["analogy_end_marker"] = "))",
      ["analogy_f"] = true,
      ["backslash_f"] = true,
      ["ignored_line_begin_marker"] = "##",
      ["ignored_line_end_marker"] = "##",
      ["numeric_tolerance_ratio"] = 0,
      ["strip_whitespace_f"] = true,
      ["whitespace_f"] = true
    },
    ["kind"] = "ConfigInst",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {
      ["chunk_type"] = "ChunkPair",
      ["title"] = "LINE_SEQUENCE/LINE_SEQUENCE"
    },
    ["kind"] = "SectionBeginInst",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {
      ["cells_n"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal"] = "alpha",
          ["relation_id"] = "OK_GOOD",
          ["subject_ref_i"] = 0,
          ["tolerance_id"] = "STRING"
        }
      },
      ["cells_s"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal_ref_i"] = 0,
          ["relation_id"] = "OK_GOOD",
          ["subject"] = "alpha",
          ["tolerance_id"] = "STRING"
        }
      },
      ["cost"] = 0.0,
      ["line_n_n"] = 1,
      ["line_n_s"] = 1
    },
    ["kind"] = "LinePairInst",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {
      ["cells_n"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal"] = "beta",
          ["relation_id"] = "BAD_SUBJECT_DIFFERS",
          ["subject_ref_i"] = 0,
          ["tolerance_id"] = "STRING"
        }
      },
      ["cells_s"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal_ref_i"] = 0,
          ["relation_id"] = "BAD_NOMINAL_DIFFERS",
          ["subject"] = "WRONG",
          ["tolerance_id"] = "STRING"
        }
      },
      ["cost"] = 1.0,
      ["line_n_n"] = 2,
      ["line_n_s"] = 2
    },
    ["kind"] = "LinePairInst",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {
      ["cells_n"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal"] = "gamma",
          ["relation_id"] = "OK_GOOD",
          ["subject_ref_i"] = 0,
          ["tolerance_id"] = "STRING"
        }
      },
      ["cells_s"] = {
        {
          ["analogy_origin_line_number_pair"] = nil,
          ["nominal_ref_i"] = 0,
          ["relation_id"] = "OK_GOOD",
          ["subject"] = "gamma",
          ["tolerance_id"] = "STRING"
        }
      },
      ["cost"] = 0.0,
      ["line_n_n"] = 3,
      ["line_n_s"] = 3
    },
    ["kind"] = "LinePairInst",
    ["signature"] = "vut-feed/1"
  },
  {
    ["field_db"] = {},
    ["kind"] = "EndOfStreamInst",
    ["signature"] = "vut-feed/1"
  },
}
