#! /usr/bin/env python3
"""SPDX-License: MIT; Project VUT; (C) Frank-Rene Schaefer

RETURN: None. Writes 'down_fixture.lua' from a REAL DOWN stream.

A fixture somebody typed would test what its author BELIEVED compare
emits. This runs the comparison and captures what it actually sent, so
the Lua suite is held against the wire and not against a memory of it.

Re-run whenever the wire shape changes; never edit the output.
"""
import asyncio, io, os, sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__),
                                "..", "..", "..", "..", ".."))
from vut.engine.compare.configuration import Configuration
from vut.engine.test_run.feed import feed_down, CollectingDisplay, down_message

SUBJECT, NOMINAL = "alpha\nWRONG\ngamma\n", "alpha\nbeta\ngamma\n"


def as_lua(value, indent=1):
    """RETURN: str, the value as a Lua table literal, keys sorted."""
    pad, deeper = "  " * indent, "  " * (indent + 1)
    if value is None:             return "nil"
    if value is True:             return "true"
    if value is False:            return "false"
    if isinstance(value, str):    return '"%s"' % value.replace('"', '\\"')
    if isinstance(value, (int, float)): return repr(value)
    if isinstance(value, list):
        if not value: return "{}"
        return "{\n" + ",\n".join(deeper + as_lua(v, indent + 1)
                                  for v in value) + "\n" + pad + "}"
    if isinstance(value, dict):
        if not value: return "{}"
        return "{\n" + ",\n".join(
            '%s["%s"] = %s' % (deeper, k, as_lua(value[k], indent + 1))
            for k in sorted(value)) + "\n" + pad + "}"
    raise TypeError("nothing Python-shaped may reach a fixture: %r" % value)


async def main():
    """RETURN: None. Captures the stream and writes the fixture."""
    adapter = CollectingDisplay()
    await feed_down(Configuration(), io.StringIO(SUBJECT),
                    io.StringIO(NOMINAL), adapter, "stdout")
    message_list = [down_message(item) for item in adapter.item_list]
    path = os.path.join(os.path.dirname(__file__), "down_fixture.lua")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("-- SPDX-License: MIT; Project VUT; (C) Frank-Rene Schaefer\n"
                 "-- " + "-" * 73 + "\n"
                 "-- A DOWN STREAM, CAPTURED FROM THE REAL COMPARE ENGINE.\n"
                 "--\n"
                 "-- GENERATED by 'generate_fixture.py', never edited: a\n"
                 "-- fixture somebody typed would test what its author\n"
                 "-- BELIEVED compare emits. Subject 'alpha/WRONG/gamma'\n"
                 "-- against nominal 'alpha/beta/gamma'.\n"
                 "-- " + "-" * 73 + "\n\n"
                 "return {\n")
        for message in message_list:
            fh.write("  " + as_lua(message) + ",\n")
        fh.write("}\n")
    print("%i messages -> down_fixture.lua" % len(message_list))

asyncio.run(main())
